### ISSUE TITLE
rbvmomi2 version 3.4.0 is missing cluster.summaryEx object

### ISSUE THREAD

**Issue by sushilrai** [ManageIQ/rbvmomi2#18]
Tried `rbvmomi2` version 3.4.0 and still the cluster object is missing `summaryEx` object. 
Need to get / set vCLS placement property which is part of `summaryEx`. 

</html>summary	ComputeResourceSummary	[summary](https://aer1-cvcsa80.asm.delllabs.net/mob/?moid=domain-c1033&doPath=summary)
**summaryEx	ClusterComputeResourceSummary**	[summaryEx](https://aer1-cvcsa80.asm.delllabs.net/mob/?moid=domain-c1033&doPath=summaryEx)

**Comment by Fryguy** [comment]
@agrare

**Comment by agrare** [comment]
Discussion from gitter :point_up: [September 29, 2022 10:53 AM](https://gitter.im/vmware/rbvmomi?at=6335b15a11a6a83d04da2a9d)

> Hey @sushilrai that is a weird one, I pulled the latest WSDL VMware vSphere Management SDK 7.0U3f
and there is no properly summaryEx in the wsdl files, it exists only in the docs to say it is deprecated yet it was added in vSphere API 7.0.1.1
the recommendation is to use computeResource.summary instead of cluserComputeResource.summaryEx per the documentation
>
> > Deprecated. Do not use this property. The cluster summary. The same information could be obtained via Summary

**Comment by sushilrai** [comment]
tried python version to pull the information of the vCLS datastore using below snippet
` if hasattr(cluster.configurationEx, 'systemVMsConfig'):
       vCLS_config = cluster.configurationEx.systemVMsConfig
    else:
      # return False, self.allowedDatastores_names, None
       return False, [], None
    changed = False`

**Comment by agrare** [comment]
This was surprising to me because I tested this property for you specifically in https://github.com/ManageIQ/rbvmomi2/pull/16

What I found was after updating the vmodl.db with the sms.wsdl for the `vSphere SMS` endpoint, it cleared the properties which were added.

**Comment by agrare** [comment]
This has been fixed in v3.4.1
