### ISSUE TITLE
RbVmomi deserialization fails on managed object type ContentLibraryItem

### ISSUE THREAD

**Issue by mahcsig** [ManageIQ/rbvmomi2#34]
**Describe the bug**
Similar to #28 but with another object

failing with:
```
/var/people/appuser/.rvm/gems/ruby-3.1.3/gems/rbvmomi2-3.6.0/lib/rbvmomi/type_loader.rb:104:in `make_type': unknown VMODL type ContentLibraryItem (RuntimeError)
```

**To Reproduce**
1. delete object from content library
2. `vim.serviceContent.taskManager.recentTask.first.info`
3. 💥

**Comment by mahcsig** [comment]
Hello @agrare , I forgot to tag you in this last week.

**Comment by agrare** [comment]
Thanks @mahcsig !  I'll take a look at this shortly.  We'll need to add these ContentLibrary classes to the vmodl.db file.

**Comment by mahcsig** [comment]
Thanks @agrare and @Fryguy!
