### ISSUE TITLE
Cannot parse "11030938062" as an int value during NIC attach parse_response

### ISSUE THREAD

**Issue by onenhansen** [ManageIQ/rbvmomi2#40]
**Describe the bug**
When running a reconfigure to add another NIC to a virtual machine, the following error occurs.  This happens in the OpenNebula vCenter driver paired with vCenter 8.0 U2. 

```
Cannot attach NIC to VM: InvalidRequest:
Cannot parse "11030938062" as an int value
while parsing serialized value of type int
at line 1, column 405
while parsing property "key" of static type int
while parsing serialized DataObject of type vim.vm.device.VirtualVmxnet3
at line 1, column 371
while parsing property "device" of static type VirtualDevice
while parsing serialized DataObject of type vim.vm.device.VirtualDeviceSpec
at line 1, column 296
while parsing property "deviceChange" of static type ArrayOfVirtualDeviceConfigSpec
while parsing serialized DataObject of type vim.vm.ConfigSpec
at line 1, column 254
while parsing call information for method ReconfigVM_Task
at line 1, column 177
while parsing SOAP body
at line 1, column 167
while parsing SOAP envelope
at line 1, column 0
while parsing HTTP request for method reconfigure
on object of type vim.VirtualMachine
at line 1, column 0.

/usr/share/one/gems-dist/gems/rbvmomi2-3.7.0/lib/rbvmomi/connection.rb:64:in `parse_response'
/usr/share/one/gems-dist/gems/rbvmomi2-3.7.0/lib/rbvmomi/connection.rb:93:in `call'
/usr/share/one/gems-dist/gems/rbvmomi2-3.7.0/lib/rbvmomi/basic_types.rb:256:in `_call'
/usr/share/one/gems-dist/gems/rbvmomi2-3.7.0/lib/rbvmomi/basic_types.rb:77:in `block (2 levels) in init'
/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:2232:in `attach_nic'
/var/lib/one/remotes/vmm/vcenter/attach_nic:73:in `<main>'"
```

**To Reproduce**
1. Import vCenter 8.0 U2 resources to OpenNebula
2. Create/Import a Virtual Machine
3. Try to attach a NIC to a virtual machine through OpenNebula

**Expected behavior**
A NIC should be attached without error

**Platform:**
 - OS: Any ( mainly testing with Ubuntu/Alma )
 - RbVmomi Version: rbvmomi2-3.7.0
 - Ruby Version: 3.0.2 ( also happens in 2.5.9 )

**Additional context**
For extra context, the function which builds and attaches the NIC can be found here in the OpenNebula project's vcenter library files: https://github.com/OpenNebula/one/blob/master/src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb#L1902

I also work on the OpenNebula project so I can provide other information if necessary. This is a very similar error that we're seeing when trying to run the old rbvmomi

**Comment by agrare** [comment]
Thanks @onenhansen I'll try to reproduce this on my side.  Could you re-run your reproducer but with SOAP debug enabled?  You can either run with the `RBVMOMI_DEBUG=1` environment variable or pass the `debug: true` option to `RbVmomi::VIM.connect()`.  This will print the raw XML to stderr.

**Comment by onenhansen** [comment]
Hi @agrare thanks for looking into this.

I've rerun this with the debug enabled in the connect method.  All of the previous requests go through properly, it gets the VM information right before this and appears to look good.  It definitely looks like it's related to the key value being interpreted as a string. Perhaps it is only a 32-bit integer and this is too large for it.  

```
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: Request:
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: 
<env:Envelope
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<env:Body>
		<ReconfigVM_Task
			xmlns="urn:vim25">
			<_this type="VirtualMachine">vm-109</_this>
			<spec xsi:type="VirtualMachineConfigSpec">
				<deviceChange xsi:type="VirtualDeviceConfigSpec">
					<operation>add</operation>
					<device xsi:type="VirtualVmxnet3">
						<key>11093059964</key>
						<deviceInfo xsi:type="Description">
							<label>net2</label>
							<summary>VM Network</summary>
						</deviceInfo>
						<backing xsi:type="VirtualEthernetCardNetworkBackingInfo">
							<deviceName>VM Network</deviceName>
							<network type="Network">network-16</network>
						</backing>
						<unitNumber>8</unitNumber>
						<addressType>manual</addressType>
						<macAddress>02:00:29:9e:bb:fa</macAddress>
					</device>
				</deviceChange>
			</spec>
		</ReconfigVM_Task>
	</env:Body>
</env:Envelope>
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: 
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: Response (in 0.003 s)
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: <?xml version="1.0" encoding="UTF-8"?>
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: <soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: <soapenv:Body>
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: <soapenv:Fault><faultcode>ServerFaultCode</faultcode><faultstring>
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: Cannot parse "11093059964" as an int value
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: 
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: while parsing serialized value of type int
Thu Nov  9 17:31:00 2023 [Z0][VMM][I]: at line 1, column 406
...
same as above past here
```

Since I wasn't involved in writing this driver I've been reading through our code to see if the key is being generated as a number higher than a 32-bit integer.

Let me know about any further information, I'll try to trace this a bit better in the next couple days.

**Comment by agrare** [comment]
Interesting so I see you're using a timestamp for the temp key https://github.com/OpenNebula/one/blame/master/src/vmm_mad/remotes/lib/vcenter_driver/virtual_machine.rb#L2031

The usual "best practice" from my experience with VM reconfigure is to use e.g. `-100` for the first new device, `-101` for the second etc...

If you replace that timestamp with `-100` does the reconfigure work?

**Comment by onenhansen** [comment]
🤦 Yep, you are right. I missed where it was generating the timestamp for the key. Gotta love problems from code written 2 years ago. I'm unsure why we haven't encountered this issue before now though.

We will change this code to generate a proper key going forward. 

Thank you for your assistance @agrare , I'll close this issue since it doesn't exist in the rbvmomi2 repo.

**Comment by agrare** [comment]
Awesome!  Glad you were able to get it working
